function coeff_mat = quadraFit(x1,y1,x2,y2,x3,y3)
    pos_x_mat = [x1^2 x1 1;...
                 x2^2 x2 1;...
                 x3^2 x3 1];
                 
    pos_y_mat = [y1;...
                 y2;...
                 y3];
                 
    coeff_mat = (pos_x_mat^(-1))*pos_y_mat;
end

